# Generated by Django 5.2.17 on 2026-09-08 03:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compromiso_hch",
                    models.BooleanField(
                        default=False, verbose_name="Compromisos de HCH"
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Tema"
                    ),
                ),
                (
                    "iniciativa",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Iniciativa"
                    ),
                ),
                ("tarea", models.TextField(verbose_name="Tarea")),
                (
                    "status",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Estado"
                    ),
                ),
                (
                    "meta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Meta",
                    ),
                ),
                (
                    "responsable_pyp",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Responsable"
                    ),
                ),
                (
                    "mes",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, verbose_name="Mes"
                    ),
                ),
                (
                    "fecha_de_compromiso",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de compromiso"
                    ),
                ),
                (
                    "fecha_de_vencimiento",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Fecha de vencimiento",
                    ),
                ),
                (
                    "fecha_real",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Fecha real"
                    ),
                ),
                (
                    "puntaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Puntaje",
                    ),
                ),
                ("primera_fecha", models.DateField(blank=True, null=True)),
                ("segunda_fecha", models.DateField(blank=True, null=True)),
                ("tercera_fecha", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "suspendida",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Suspendida"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "compromisos",
                "ordering": ["-created_at"],
                "permissions": [
                    ("restore_compromiso", "Puede restaurar compromisos"),
                    ("purge_compromiso", "Puede eliminar definitivamente"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistorialCompromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("usuario", models.CharField(max_length=150)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "compromiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="compromisos.compromiso",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Reprogramacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_reprogramacion", models.PositiveIntegerField()),
                ("fecha_anterior", models.DateField(blank=True, null=True)),
                ("fecha_nueva", models.DateField()),
                ("motivo", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=150)),
                (
                    "compromiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reprogramaciones",
                        to="compromisos.compromiso",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_reprogramacion"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("compromiso", "numero_reprogramacion"),
                        name="reprogramacion_numero_unico",
                    )
                ],
            },
        ),
    ]
