# Generated by Django 5.2.17 on 2026-09-09 03:47

from django.db import migrations, models



def actualizar(apps, schema_editor):
    C = apps.get_model("compromisos", "Compromiso")
    E = apps.get_model("compromisos", "Estado")
    H = apps.get_model("compromisos", "HistorialCompromiso")
    db = schema_editor.connection.alias
    for code, label in [("EC", "En curso"), ("S", "Suspendido"), ("T", "Terminado"), ("D", "Demorado")]:
        E.objects.using(db).update_or_create(codigo=code, defaults={"nombre": label, "activo": True})
    E.objects.using(db).exclude(codigo__in=["EC", "S", "T", "D"]).update(activo=False)
    for c in C._base_manager.using(db).all().iterator():
        old = (c.status, c.primera_fecha, c.fecha_de_vencimiento, c.suspendida)
        first = c.primera_fecha or c.fecha_de_vencimiento
        status = "S" if c.suspendida or c.status == "S" else c.status if c.status in ["EC", "T", "D"] else "EC"
        due = c.tercera_fecha or c.segunda_fecha or first
        if old != (status, first, due, status == "S"):
            C._base_manager.using(db).filter(pk=c.pk).update(status=status, primera_fecha=first, fecha_de_vencimiento=due, suspendida=status == "S")
            H.objects.using(db).create(compromiso_id=c.pk, accion="ACTUALIZADO", usuario="sistema",
                descripcion=f"Normalización de estatus y vencimiento automático. Antes (estatus, primera fecha, vencimiento, suspendida): {old}. Después: {(status, first, due, status == 'S')}.")

class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0002_cumplimiento_fechas'),
    ]

    operations = [
        migrations.RunPython(actualizar),
        migrations.AlterField(
            model_name='compromiso',
            name='fecha_de_vencimiento',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='status',
            field=models.CharField(choices=[('EC', 'En curso'), ('S', 'Suspendido'), ('T', 'Terminado'), ('D', 'Demorado')], db_index=True, max_length=30, verbose_name='Estatus'),
        ),
    ]
