# Generated by Django 5.2.17 on 2026-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0004_estatus_automatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioTeams',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('corte', models.DateField()),
                ('total', models.PositiveIntegerField()),
                ('estado', models.CharField(default='en_curso', max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
