# Generated by Django 5.2.17 on 2026-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0005_envioteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='jefatura',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Jefatura'),
        ),
    ]
