# Generated by Django 5.2.17 on 2026-09-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0006_compromiso_jefatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='jefatura',
            field=models.CharField(blank=True, choices=[('Jefatura de Facturacion a Clientes', 'Jefatura de Facturacion a Clientes'), ('Jefatura de Soporte Oper Post Facturacion', 'Jefatura de Soporte Oper Post Facturacion'), ('Jefatura de Control y Mejoras de Facturacion', 'Jefatura de Control y Mejoras de Facturacion')], default='', max_length=150, verbose_name='Jefatura'),
        ),
    ]
