# Generated by Django 5.2.17 on 2026-10-01 02:51

import django.db.models.deletion
from django.db import migrations, models


def copiar(apps, schema_editor):
    alias = schema_editor.connection.alias
    Event = apps.get_model('compromisos', 'EventoCompromiso')
    Send = apps.get_model('compromisos', 'EnvioNotificacion')
    for name, tipo in [('HistorialCompromiso', 'historial'), ('Reprogramacion', 'reprogramacion')]:
        Old = apps.get_model('compromisos', name)
        for row in Old.objects.using(alias).all().iterator():
            fields = dict(compromiso_id=row.compromiso_id, tipo=tipo, origen_id=row.pk)
            if tipo == 'historial':
                fields.update(accion=row.accion, descripcion=row.descripcion, usuario=row.usuario)
                fecha = row.fecha
            else:
                fields.update(numero_reprogramacion=row.numero_reprogramacion, fecha_anterior=row.fecha_anterior, fecha_nueva=row.fecha_nueva, motivo=row.motivo, usuario=row.created_by)
                fecha = row.created_at
            new = Event.objects.using(alias).create(**fields)
            Event.objects.using(alias).filter(pk=new.pk).update(fecha=fecha)
        if Event.objects.using(alias).filter(tipo=tipo).count() != Old.objects.using(alias).count():
            raise RuntimeError('No coincide el total de eventos migrados')
    for name, canal in [('EnvioTeams', 'teams'), ('EnvioCorreo', 'correo')]:
        Old = apps.get_model('compromisos', name)
        for row in Old.objects.using(alias).all().iterator():
            new = Send.objects.using(alias).create(canal=canal, token=row.pk, usuario=row.usuario, corte=row.corte, estado=row.estado, total=getattr(row, 'total', None))
            Send.objects.using(alias).filter(pk=new.pk).update(creado=row.creado)
        if Send.objects.using(alias).filter(canal=canal).count() != Old.objects.using(alias).count():
            raise RuntimeError('No coincide el total de envíos migrados')
    # Preserve existing group and individual grants; legacy permissions remain for rollback.
    CT = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    GroupGrant = apps.get_model('auth', 'Group').permissions.through
    UserGrant = apps.get_model('auth', 'User').user_permissions.through
    for target, sources in [('eventocompromiso', ['historialcompromiso', 'reprogramacion']), ('envionotificacion', ['envioteams', 'enviocorreo'])]:
        ct, _ = CT.objects.using(alias).get_or_create(app_label='compromisos', model=target)
        for action in ['view', 'add', 'change', 'delete']:
            permission, _ = Permission.objects.using(alias).get_or_create(content_type=ct, codename=f'{action}_{target}', defaults={'name': f'Can {action} {target}'})
            old_ids = Permission.objects.using(alias).filter(content_type__app_label='compromisos', codename__in=[f'{action}_{s}' for s in sources]).values_list('pk', flat=True)
            for group_id in GroupGrant.objects.using(alias).filter(permission_id__in=old_ids).values_list('group_id', flat=True).distinct():
                GroupGrant.objects.using(alias).get_or_create(group_id=group_id, permission_id=permission.pk)
            for user_id in UserGrant.objects.using(alias).filter(permission_id__in=old_ids).values_list('user_id', flat=True).distinct():
                UserGrant.objects.using(alias).get_or_create(user_id=user_id, permission_id=permission.pk)


def restaurar(apps, schema_editor):
    from django.core.management.color import no_style
    alias = schema_editor.connection.alias
    Event = apps.get_model('compromisos', 'EventoCompromiso')
    Send = apps.get_model('compromisos', 'EnvioNotificacion')
    restored = []
    for name, tipo in [('HistorialCompromiso', 'historial'), ('Reprogramacion', 'reprogramacion')]:
        Old = apps.get_model('compromisos', name)
        rows = Event.objects.using(alias).filter(tipo=tipo)
        # Reserve all original IDs before allocating IDs for records created after migration.
        next_id = max(rows.values_list('origen_id', flat=True).exclude(origen_id=None), default=0) + 1
        for row in rows.iterator():
            pk = row.origen_id
            if pk is None:
                pk, next_id = next_id, next_id + 1
            fields = dict(id=pk, compromiso_id=row.compromiso_id)
            if tipo == 'historial':
                fields.update(accion=row.accion, descripcion=row.descripcion, usuario=row.usuario)
                date_field = 'fecha'
            else:
                fields.update(numero_reprogramacion=row.numero_reprogramacion, fecha_anterior=row.fecha_anterior, fecha_nueva=row.fecha_nueva, motivo=row.motivo, created_by=row.usuario)
                date_field = 'created_at'
            Old.objects.using(alias).create(**fields)
            Old.objects.using(alias).filter(pk=pk).update(**{date_field: row.fecha})
        restored.append(Old)
    for name, canal in [('EnvioTeams', 'teams'), ('EnvioCorreo', 'correo')]:
        Old = apps.get_model('compromisos', name)
        for row in Send.objects.using(alias).filter(canal=canal).iterator():
            fields = dict(id=row.token, usuario=row.usuario, corte=row.corte, estado=row.estado)
            if canal == 'teams':
                fields['total'] = row.total
            Old.objects.using(alias).create(**fields)
            Old.objects.using(alias).filter(pk=row.token).update(creado=row.creado)
    with schema_editor.connection.cursor() as cursor:
        for sql in schema_editor.connection.ops.sequence_reset_sql(no_style(), restored):
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0008_enviocorreo'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('teams', 'Teams'), ('correo', 'Correo')], max_length=10)),
                ('token', models.UUIDField(editable=False)),
                ('usuario', models.CharField(max_length=150)),
                ('corte', models.DateField()),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='en_curso', max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('historial', 'Historial'), ('reprogramacion', 'Reprogramación')], db_index=True, default='historial', max_length=20)),
                ('origen_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('accion', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_reprogramacion', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_anterior', models.DateField(blank=True, null=True)),
                ('fecha_nueva', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='envionotificacion',
            constraint=models.UniqueConstraint(fields=('canal', 'token'), name='envio_canal_token_unico'),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='compromisos.compromiso'),
        ),
        migrations.AddConstraint(
            model_name='eventocompromiso',
            constraint=models.UniqueConstraint(fields=('tipo', 'origen_id'), name='evento_origen_unico'),
        ),
        migrations.AddConstraint(
            model_name='eventocompromiso',
            constraint=models.UniqueConstraint(fields=('compromiso', 'numero_reprogramacion'), name='evento_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='eventocompromiso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('numero_reprogramacion__isnull', True), ('tipo', 'historial')), models.Q(('fecha_nueva__isnull', False), ('numero_reprogramacion__isnull', False), ('tipo', 'reprogramacion')), _connector='OR'), name='evento_tipo_campos_validos'),
        ),
        migrations.RunPython(copiar, restaurar),
        migrations.DeleteModel(
            name='EnvioCorreo',
        ),
        migrations.DeleteModel(
            name='EnvioTeams',
        ),
        migrations.DeleteModel(
            name='HistorialCompromiso',
        ),
        migrations.DeleteModel(
            name='Reprogramacion',
        ),
    ]
