# Generated by Django 5.2.17 on 2026-10-01 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0009_consolidar_tablas'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('sessions', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocompromiso',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'registro del portal', 'verbose_name_plural': 'registros del portal'},
        ),
        migrations.RemoveConstraint(
            model_name='eventocompromiso',
            name='evento_tipo_campos_validos',
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='action_flag',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='canal',
            field=models.CharField(blank=True, choices=[('teams', 'Teams'), ('correo', 'Correo')], max_length=10),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='change_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_admin', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='corte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='estado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='estado_id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='expire_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='object_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='session_data',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='session_key',
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocompromiso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventocompromiso',
            name='compromiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='compromisos.compromiso'),
        ),
        migrations.AlterField(
            model_name='eventocompromiso',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventocompromiso',
            name='tipo',
            field=models.CharField(choices=[('historial', 'Historial'), ('reprogramacion', 'Reprogramación'), ('estado', 'Estado configurable'), ('envio', 'Envío'), ('sesion', 'Sesión'), ('admin', 'Auditoría administrativa')], db_index=True, default='historial', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventocompromiso',
            name='usuario',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name='eventocompromiso',
            constraint=models.UniqueConstraint(fields=('canal', 'token'), name='registro_envio_unico'),
        ),
        migrations.AddConstraint(
            model_name='eventocompromiso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('compromiso__isnull', False), ('numero_reprogramacion__isnull', True), ('tipo', 'historial')), models.Q(('compromiso__isnull', False), ('fecha_nueva__isnull', False), ('numero_reprogramacion__isnull', False), ('tipo', 'reprogramacion')), models.Q(('codigo__isnull', False), ('tipo', 'estado')), models.Q(('canal__in', ['teams', 'correo']), ('corte__isnull', False), ('tipo', 'envio'), ('token__isnull', False)), models.Q(('expire_date__isnull', False), ('session_key__isnull', False), ('tipo', 'sesion')), models.Q(('action_flag__in', [1, 2, 3]), ('tipo', 'admin'), ('user__isnull', False)), _connector='OR'), name='registro_tipo_campos_validos'),
        ),
        migrations.AlterModelTable(
            name='eventocompromiso',
            table='registros_portal',
        ),
    ]
