# Generated by Django 5.2.17 on 2026-10-06 04:16

from django.db import migrations, models


def renombrar_stand_by(apps, schema_editor):
    EventoCompromiso = apps.get_model("compromisos", "EventoCompromiso")
    EventoCompromiso.objects.filter(tipo="estado", codigo="S").update(
        nombre="Stand By"
    )


def restaurar_suspendido(apps, schema_editor):
    EventoCompromiso = apps.get_model("compromisos", "EventoCompromiso")
    EventoCompromiso.objects.filter(tipo="estado", codigo="S").update(
        nombre="Suspendido"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('compromisos', '0016_clave_reprogramacion_oracle'),
    ]

    operations = [
        migrations.RunPython(renombrar_stand_by, restaurar_suspendido),
        migrations.AlterField(
            model_name='compromiso',
            name='status',
            field=models.CharField(choices=[('EC', 'En curso'), ('S', 'Stand By'), ('T', 'Terminado'), ('D', 'Demorado')], db_index=True, max_length=30, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='suspendida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Stand By'),
        ),
    ]
