# Generated by Django 5.2.17 on 2026-10-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compromisos", "0011_consolidar_almacenamiento"),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
